name: canasta
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/canasta_icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode" 

flutter:
  assets:
    - "assets/images/canasta_icon.jpg"
    - "assets/images/3-of-Hearts.jpg"
    - "assets/images/3-of-Diamonds.jpg"
  fonts:
    - family: Satoshi
      fonts: 
        - asset: custom_fonts/fonts/Satoshi-Variable.ttf
          weight: 600
  uses-material-design: true

  