name: canasta
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Satoshi
      fonts: 
        - asset: custom_fonts/fonts/Satoshi-Variable.ttf
          weight: 600
  uses-material-design: true

